export const requestGlobalObject = {
    FilterIdCategoria:null,
    PaginationSettings:null,
    UnidadNegocioCaller: null,
    APP_ConfigurationID:"20007",
    Platform:"Android",
    AppVersion:"1.0.0,1.0.0",
    AppDebug:false,
    Fecha: new Date().toISOString(),
    IdSucursal:null,
    SucursalCompra:null,
    ModeEmpresas:false,
    MobileMonoMarca:false,
    IdEmpresa:0,
    Lng:null,
    Lat:null,
    Alt:null,
    ReadCountMode:false,
    PageFrom:null,
    PageCount:null,
    CalculateTotalRows:false,
    LastId:0
}